FROM nginx:latest

COPY ./challenge/nginx.conf /etc/nginx/nginx.conf
COPY ./challenge/default.conf /etc/nginx/conf.d/default.conf
COPY ./challenge/static /var/www/app/static
COPY ./challenge/private /var/www/app/private
