version: '3'
services:
  iter_fold:
    build:
      context: .
    restart:  always
    working_dir: /home/pwn
    container_name: iter_fold 
    ulimits:
      nproc: 65535
      core: 0
    ports:
        - "4004:4004"
    entrypoint: /etc/init.sh
