version: '3'
services:
  stuck:
    build:
      context: .
    restart:  always
    working_dir: /home/pwn
    container_name: stuck
    ulimits:
      nproc: 65535
      core: 0
    ports:
        - "4000:4000"
    entrypoint: /etc/init.sh
